const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  DIRECTOR: "DIRECTOR",
  MANAGER: "MANAGER",
  ACCOUNTANT: "ACCOUNTANT",
  SALES_EXECUTIVE: "SALES_EXECUTIVE",
  DEALER: "DEALER",
  PAINTER: "PAINTER",
};

module.exports = ROLES;